[package]
name = "clippy_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc_hir = { path = "../rustc_hir" }
rustc_lint = { path = "../rustc_lint" }
rustc_span = { path = "../rustc_span" }
